name: CI

on:
  push:
    branches:
      - master
      - /^feature\/.*$/
      - '!refs/pull/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install
      run: npm install
    - name: Build & tests
      run: npm run build
